# Generated by Django 5.2.3 on 2025-07-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_consuming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
